[package]
name = "ballistic"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17.0", features = ["wgpu", "ndarray", "autodiff"] }
chrono = "0.4.41"
rand = "0.9.1"
ringbuffer = "0.15.0"
rocketsim_rs = "0.35.2"
serde = "1.0.219"
